### ISSUE TITLE
Telegram Bot V2

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity-os-marketplace/ubiquity-os-kernel-telegram#1]
This plugin is designed to process events from both Telegram and GitHub, enabling it to respond flexibly and making it more scalable than a configuration limited to handling Telegram events and kernel interactions alone.

The system will function as the 'kernel' for Telegram, intended for use potentially within just our organization or alongside partners, depending on the final design.

All essential logic from Version 1 (V1) will be refactored to be compatible with the new Version 2 (V2) kernel. Initially, it will incorporate the functionality specified in https://github.com/ubiquibot/plugins-wishlist/issues/25.

It aims to provide a robust foundation that can be expanded with additional features. Comprehensive documentation will be developed to facilitate rapid onboarding, ensuring a seamless transition to align with the capabilities of V1.

- [x] Build foundations
- [x] Build Workrooms feature
- [x] Build DM Notifications
- [x] Integrate `/ask` via https://github.com/ubiquity-os-marketplace/ubiquity-os-kernel-telegram/issues/17

**Comment by Keyrxng** [comment]
Now that #2 is merged this spec can be expanded on and the features that are required to be ported over should be listed here. It's unclear to me what features are wanted in this new version compared to V1.

All other aspects of my initial spec have been met.

@rndquu @gentlementlegen @0x4007 rfc, thank you.

**Comment by 0x4007** [comment]
> rfc

What is your question?

**Comment by Keyrxng** [comment]
> It's unclear to me what features are wanted in this new version compared to V1

What features exactly from V1 need ported over? All of them as they exist in V1 or

**Comment by 0x4007** [comment]
Nobody knows as well as you. List every feature in "v1" and write a proposal for what to add in "v2"
