### ISSUE TITLE
DM notifications

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity-os-marketplace/ubiquity-os-kernel-telegram#13]
It was proposed that I enable UbiquityOS to be able to communicate directly with our userbase via Telegram direct messages.

As the first step I propose that we build out four triggers
- Payment
- Review
- Reminder
- Disqualification

Payment - Will parse the permit comment posted by UbiquityOS (Permit DB storage broken so cannot use that)
Reminder - Will parse the follow-up comment posted by UbiquityOS
Disqualification - Will read from `issues.unassigned`
Review - Will read from `pull_request.review_requested`

this feature will be built using the `bot api`, so is not a MTProtoAPI/Personal Account reliant feature however it's likely that the user must have previously communicated with our bot on Telegram so that the connection exists for it to have that permission. This is a requirement of registering however so should be error-free.

- `/register keyrxng` will be a new Telegram bot slash command added through this feature which will allow a user to bind their GitHub account to their Telegram account.
- `/subscribe` will open a dynamic list of buttons for all of the functional triggers. Select to enable.
- `/unsubscribe` does the same as above but disables the triggers

_can't find the related context_

**Comment by 0x4007** [comment]
I suppose it could be interesting to "subscribe" to the "classname" of the metadata that is embedded in the bot comments. That way when we roll out new capabilities or "events" we can easily subscribe without having to update the Telegram related code?

**Comment by Keyrxng** [comment]
Sounds good but there is more to consider

- The bot doesn't know the classnames or have associated text to use per that reminder.

- They can be configurable along with the classnames passed via the config as a single object. Or a standardized notification template can be used

- Some notifications are based on webhook events as opposed to comment parsing, so comment-based ones could be automated like your suggesting

- I think the four I've done cover everything that we need right now but if you think of more reasons you want a DM from the bot I can write a spec for it.


Since we do not have stable comment metadata or a parser yet, building this feature should be a separate task.

**Comment by 0x4007** [comment]
Telegram user should tell the bot the class name. Unfortunately we would need to uncover the metadata in the comment source code, or plugin source code to know. However this is useful in the short-to-mid term as we are in active development across multiple plugins. 

The metadata setter and getter is standardized and was added to the SDK from what I was told. The class names are up to the discretion of the plugin developer but over time we should see this coalesce per plugin.

**Comment by Keyrxng** [comment]
> Telegram user should tell the bot the class name

Are you suggesting I as a plugin developer should say `/subscribe myPluginHeader` and that's me subscribed to it's comment postings and it should feed me the entire `structuredMetadata` object that logged? And contributors would say `/subscribe payment`?

![image](https://github.com/user-attachments/assets/58f9b892-bb2c-41f2-a662-eb2fd9c8ecf9)

This is how things are presented right now. 

> The metadata setter and getter is standardized and was added to the SDK from what I was told. The class names are up to the discretion of the plugin developer but over time we should see this coalesce per plugin.

Oh cool I didn't know it was good to go. I'll open a task and completely re-do the `issues_comment.created` handler inline with your suggestion of parsing every bot comment for dynamically for a header and treating every header as a notification to be sent. It'll require quite a bit of thought and work.

**Comment by Keyrxng** [comment]
Can this be priced, assigned and reward generated for me when you have the chance please? Cheers.

QA of feature working and installed: https://github.com/ubiquity-os-marketplace/ubiquity-os-kernel-telegram/pull/23#issuecomment-2445378482

**Comment by Keyrxng** [comment]
> ```diff
> ! chat_not_found
> ```

@0x4007 What should the behaviour be for this?

1. We create a workroom if it doesn't exist
2. We do nothing
3. We check if there is a linked merged PR and try to determine if it's redundant opening a workroom and handle it dynamically?

**Comment by 0x4007** [comment]
> > ```diff
> 
> > ! chat_not_found
> 
> > ```
> 
> 
> 
> @0x4007 What should the behaviour be for creating a room on `reopen`?
> 
> 
> 
> 1. We create a workroom if it doesn't exist
> 
> 2. We do nothing
> 
> 3. We check if there is a linked merged PR and try to determine if it's redundant opening a workroom and handle it dynamically? 

It shouldn't do anything. We just scroll up to rejoin if we need to.

**Comment by gentlementlegen** [comment]
@Keyrxng i guess this happens because these are actions running and get delay?

**Comment by Keyrxng** [comment]
Yes it was mate. I changed the status on the error so it's stopped being posted for now but this double comment was an action delay I'm sure
