### ISSUE TITLE
Testing chat creation

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity-os-marketplace/ubiquity-os-kernel-telegram#5]
Just a test to see if the chat is created.

**Comment by gentlementlegen** [comment]
Runs work but do nothing so far https://github.com/ubiquity-os-marketplace/ubiquity-os-kernel-telegram/actions/runs/11304580763
Could be due to the auth.

**Comment by 0x4007** [comment]
I guess it would make sense to only make a chat room on assignment
